import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft } from 'lucide-react';

const Section = ({ title, children }) => (
  <section className="mb-8">
    <h2 className="text-base font-bold text-white mb-3">{title}</h2>
    <div className="text-sm leading-relaxed space-y-2" style={{ color: '#94A3B8' }}>
      {children}
    </div>
  </section>
);

const Terms = () => (
  <div className="min-h-screen" style={{ background: '#0F172A' }}>
    <div className="max-w-2xl mx-auto px-6 py-12">
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, ease: 'easeOut' }}
      >
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 text-sm mb-8 transition-colors"
          style={{ color: '#475569' }}
          onMouseEnter={e => { e.currentTarget.style.color = '#94A3B8'; }}
          onMouseLeave={e => { e.currentTarget.style.color = '#475569'; }}
        >
          <ArrowLeft size={14} /> Back to home
        </Link>

        <h1 className="text-2xl font-black text-white mb-1">Terms of Service</h1>
        <p className="text-xs mb-10" style={{ color: '#475569' }}>Last updated: April 2025</p>

        <Section title="1. Acceptance of Terms">
          <p>By accessing or using Tcent.AI, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>Tcent.AI provides AI-powered career growth tools for working professionals, including ATS resume analysis, career path recommendations, personality assessments, and an AI career advisor.</p>
        </Section>

        <Section title="3. User Accounts">
          <p>You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information when creating your account. You may not share your account with others.</p>
        </Section>

        <Section title="4. Acceptable Use">
          <p>You agree not to misuse the platform, attempt to reverse-engineer or scrape our AI models or data, upload malicious files, or use the service for any unlawful purpose.</p>
        </Section>

        <Section title="5. Your Content">
          <p>You retain ownership of any content you upload (such as your resume). By uploading, you grant Tcent.AI a limited licence to process and store your content solely to provide the service.</p>
        </Section>

        <Section title="6. AI-Generated Content">
          <p>Career advice and recommendations generated by our AI are for informational purposes only and do not constitute professional career counselling, legal, or financial advice. Results may vary.</p>
        </Section>

        <Section title="7. Intellectual Property">
          <p>All platform code, design, branding, and AI models are the property of Tcent.AI. Nothing in these terms grants you a right to use our brand or intellectual property.</p>
        </Section>

        <Section title="8. Disclaimers and Limitation of Liability">
          <p>The service is provided "as is" without warranties of any kind. To the maximum extent permitted by law, Tcent.AI shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform.</p>
        </Section>

        <Section title="9. Changes to Terms">
          <p>We may update these terms. Continued use of the platform after changes take effect constitutes your acceptance of the revised terms.</p>
        </Section>

        <Section title="10. Contact">
          <p>Questions about these terms? Email us at <a href="mailto:info@tcent.ai" className="underline hover:text-white transition-colors">info@tcent.ai</a>.</p>
        </Section>
      </motion.div>
    </div>
  </div>
);

export default Terms;
